**ARRAYS**

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float

In [3]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    array1 = numpy.array(arr[::-1],float)
    return array1

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


**SHAPE AND RESHAPE**

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

In [4]:
import numpy as np


my_array = np.array(input().split(),int)

print(np.reshape(my_array,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**MEAN,VAR AND STD**

You are given a 2-D array of size NXM.
Your task is to find:

The mean along axis 1
The var along axis 0
The std along axis None

In [6]:
import numpy
numpy.set_printoptions(legacy='1.13')
N,M = list(map(int,input().strip().split()))
my_array = numpy.array([input().strip().split() for _ in range(N)],int)
print(numpy.mean(my_array,axis=1))
print(numpy.var(my_array,axis=0))
print(numpy.std(my_array,axis = None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


**Transpose and Flatten**

You are given a NXM integer array matrix with space separated elements ( N= rows and  M= columns).
Your task is to print the transpose and flatten results.

In [8]:
import numpy

N, M = list(map(int, input().split()))


my_array = numpy.array([input().split() for _ in range(N)],int)

print(numpy.transpose(my_array))
print(my_array.flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


**Concatenate**

You are given two integer arrays of size NXP and MXP (N & M are rows, and P is the column). Your task is to concatenate the arrays along axis 0

In [9]:
import numpy
n,m,p = list(map(int,input().split()))
array_1 = numpy.array([input().split() for _ in range(n)],int)
array_2 = numpy.array([input().split() for _ in range(m)],int)

print(numpy.concatenate([array_1,array_2],axis=0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


**Zeros and Ones**

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones

In [10]:
import numpy

size = list(map(int,input().split()))
print(numpy.zeros(size,dtype = int))
print(numpy.ones(size,dtype = int))


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


**Eye and Identity**

The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter k . A positive k  is for the upper diagonal, a knegative  is for the lower, and a  0 k (default) is for the main diagonal.

In [11]:
import numpy
numpy.set_printoptions(legacy='1.13')
n,m = list(map(int,input().split()))
print(numpy.eye(n,m))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


**ARRAY MATHEMATICS**

You are given two integer arrays, A and B  of dimensions NXN.
Your task is to perform the following operations:

Add (A + B)
Subtract (A -B )
Multiply ( A*B )
Integer Division (A /B )
Mod ( A% B)
Power ( A**B )

In [21]:
import numpy
N,M = list(map(int,input().split()))
A = numpy.array([input().split() for _ in range(N)],int)
B = numpy.array([input().split() for _ in range(N)],int)
print(numpy.add(A,B))
print(numpy.subtract(A,B))
print(numpy.multiply(A,B))
print(A//B)
print(numpy.mod(A,B))
print(numpy.power(A,B))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


**Floor, Ceil, Rint**

You are given a 1-D array,A . Your task is to print the FLOOR,CEIL  and RINT of all the elements of A 

In [20]:
import numpy
numpy.set_printoptions(legacy='1.13')
my_array = numpy.array(input().split(),float)

print(numpy.floor(my_array))
print(numpy.ceil(my_array))
print(numpy.rint(my_array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


**Sum and Product**

You are given a 2-D array with dimensions NXM.
Your task is to perform the SUM tool over axis 0   and then find the PRODUCTof that result

In [19]:
import numpy

n,m = list(map(int,input().split()))
my_array = numpy.array([input().split() for _ in range(n)],int)
arr1 =  numpy.sum(my_array,axis =0)

print(numpy.prod(arr1))

2 2
1 2
3 4
24


**Min and Max**

You are given a 2-D array with dimensions N X M.
Your task is to perform the min function over axis 11   and then find the max of that.

In [18]:
import numpy

N,M = list(map(int,input().split()))
my_array = numpy.array([input().split() for _ in range(N)],int)
arr1 = numpy.min(my_array,axis=1)

print(numpy.max(arr1))

4 2
2 5
3 7
1 3
4 0
3


**DOT AND CROSS**


You are given two arrays A and B. Both have dimensions of NXN.
Your task is to compute their matrix product.

In [15]:
import numpy
numpy.set_printoptions(legacy='1.13')
N=int(input())
A = numpy.array([input().split() for _ in range(N)],int)
B = numpy.array([input().split() for _ in range(N)],int)
print(numpy.matmul(A,B))



2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


**INNER AND OUTER**

You are given two arrays: A and B .
Your task is to compute their inner and outer product.

In [14]:
import numpy

A = numpy.array(input().split(),int)
B = numpy.array(input().split(),int)

print(numpy.inner(A,B))
print(numpy.outer(A,B)) 

0 1
2 3
3
[[0 0]
 [2 3]]


**Polynomials**

You are given the coefficients of a polynomial P.
Your task is to find the value of P at point x .

In [13]:
import numpy

P = list(map(float,input().split()))
x = int(input())
print(numpy.polyval(P,x))

1.1 2 3
0
3.0


**Linear Algebra**

The first line contains the integer N .
The next N  lines contains the N space separated elements of array A .

In [12]:
import numpy

N = int(input())
A = numpy.array([input().split() for _ in range(N)],float)
print(round(numpy.linalg.det(A)))

2
1.1 1.1
1.1 1.1
0
